### ISSUE TITLE
华南金牌  X79 E5-2640  GTX1060 

### ISSUE THREAD

**Issue by Leozgu** [wy414012/huaNan_x79_e5_2670_v1_c2#1]
大佬你好 
我的配置是华南金牌  X79 E5-2640  GTX1060 
我用你的efi试了一下 目前来说试过的efi里你这个是白苹果读条那里是能动的（其他试过都是卡在白苹果都条 没有动静） 虽然还是不能安装 
这是报错代码
![WechatIMG444](https://user-images.githubusercontent.com/80804904/111415077-2c7aa000-871c-11eb-9969-db3d73481477.jpeg)
用的是 v-os10.15.7版本的clover

进度是跑到这个位置报错的
![WechatIMG35](https://user-images.githubusercontent.com/80804904/111415387-c5a9b680-871c-11eb-943b-df08b5c43be2.jpeg) 之前用的efi 完全不能动。。。

**Comment by wy414012** [comment]
hfs清前往gitee下载最新版本，github中默认现在推送很难！
