### ISSUE TITLE
你好，我的X79安装卡在这个地方，请问是什么原因呢？【已解决硬盘兼容问题】

### ISSUE THREAD

**Issue by 1013461195** [wy414012/huaNan_x79_e5_2670_v1_c2#17]
使用的是您的0.75引导，系统是11.6
![image](https://user-images.githubusercontent.com/23392657/140268073-b621bb93-cd1a-404c-b94a-ff9fac7e331c.png)

**Comment by wy414012** [comment]
@1013461195 检查磁盘模式调整为ahci ，检查EFI路径是不是由于CI打包错误导致oepncore.efi路径不正确，添加[AppleMCEReporterDisabler.kext](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2/tree/master/%E6%97%A7kext/AppleMCEReporterDisabler.kext)并且启用。
