### ISSUE TITLE
E5 2643V2CPU核心数量无法正常识别导致报错

### ISSUE THREAD

**Issue by exqmjmz** [wy414012/huaNan_x79_e5_2670_v1_c2#18]
大佬您好！
电脑配置是华南X79 CPU E5 2643V2 显卡AMD R7 270
用的最新0.77，启动后报截图中的错误。
初步判断感觉是无法正常识别核心数量，这个该如何修复？
"x86_validate_topology() 12 threads but 13 registered from MADT"
![image](https://user-images.githubusercontent.com/12406935/150633463-78642ea7-d26c-41ec-8599-44721942afa6.png)

**Comment by wy414012** [comment]
@ljm000 该问题属于内部固件错误～需要进行修复，华南x79版型很多，请添加详细信息，不然无法处理

**Comment by ljm000** [comment]
华南x79－6m
![Screenshot_2022-01-22-20-04-49-707_com taobao taobao](https://user-images.githubusercontent.com/12406935/150640600-a4019fcd-e77e-40a7-af22-97ff2f003b4b.jpg)

**Comment by exqmjmz** [comment]
用e5 2670v2可以正常安装和进系统

**Comment by exqmjmz** [comment]
> @ljm000 该问题属于内部固件错误～需要进行修复，华南x79版型很多，请添加详细信息，不然无法处理

华南x79－6m
![Uploading Screenshot_2022-01-22-20-04-49-707_com.taobao.taobao.jpg…]()

**Comment by exqmjmz** [comment]
![Screenshot_2022-01-22-20-04-49-707_com taobao taobao](https://user-images.githubusercontent.com/12406935/150643334-a9dcd54d-d335-44e0-bf00-f50c3667051b.jpg)

**Comment by exqmjmz** [comment]
[acpi-origin.zip](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2/files/7923465/acpi-origin.zip)
这个是通过clover导出的acpi原始文件

**Comment by wy414012** [comment]
`            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                Zero
                Zero
                Zero
                Zero
                Zero
                Zero
                Zero
                Zero
                Zero
                Zero
                Zero
                Zero
                Zero
                Zero
                Local0 = PSTA (Zero)
                Local1 = (Local0 & 0x03)
                LSTA = Local1
                Return (Local0)
            }`这里很明显的错误，正常应该为`            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                CUU0 = "CPUSCK0"
                Local0 = PSTA (Zero)
                Local1 = (Local0 & 0x03)
                LSTA = Local1
                Return (Local0)
            }`

**Comment by wy414012** [comment]
可以参考该文件进行修复以及屏蔽多余未使用
[DSDT.dsl.zip](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2/files/7923910/DSDT.dsl.zip)
的
