### ISSUE TITLE
Why need SSDT-PMC here?

### ISSUE THREAD

**Issue by Drovosek01** [wy414012/huaNan_x79_e5_2670_v1_c2#19]
Hello.

Many thanks for the published files. I have the same processor with a QIYADA x79 and RX580 4GB motherboard and according to the guide from dortania I couldn't even get to the macOS Monterey installation screen

It is written everywhere that SSDT-PMC is needed for NVRAM on 300 series motherboards.

Why is this file used here?

**Comment by wy414012** [comment]
PMC description exists in my firmware even in most x79 firmware, so it should be necessary here. The original code in the firmware`     Device (ZPMC)
        {
            Name (_HID, EisaId ("ITMC032"))  // _HID: Hardware ID
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                    Return (Zero)
                }
            }

            Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
            {
                Memory32Fixed (ReadWrite,
                    0xFE000000,         // Address Base
                    0x00010000,         // Address Length
                    )
            })
        }`
This code comes from the dsdt in the firmware of my motherboard, so it is theoretically necessary to exist.
