### ISSUE TITLE
mac 12重启多次才能进入系统，13提示不支持[已完成]

### ISSUE THREAD

**Issue by kittyzero520** [wy414012/huaNan_x79_e5_2670_v1_c2#20]
设备
cpu：e5-1650v2
ram：ddr 64g
显卡：rx580

mac 12重启多次才能进入系统，13提示不支持

那个cpu描述不知道怎么改

**Comment by wy414012** [comment]
QQ群里面艾特群主 我帮你解决这问题

**Comment by kittyzero520** [comment]
> QQ群里面艾特群主我帮你解决这个问题

QQ号多少，怎么给你们发个9.9红包

**Comment by wy414012** [comment]
文档上面有支持群，里面也全是x79用户

**Comment by kittyzero520** [comment]
> QQ群里面艾特群主 我帮你解决这问题

我艾特了

**Comment by kittyzero520** [comment]
![1](https://user-images.githubusercontent.com/33313886/230306302-c72b69ff-32be-4574-bb74-6d95eaa08be6.png)
