### ISSUE TITLE
Reboot loop after completely Sonoma Install

### ISSUE THREAD

**Issue by fromage9747** [wy414012/huaNan_x79_e5_2670_v1_c2#22]
Hi there,

I just want to thank you for this awesome work you have put into this EFI.  Absolutely amazing.  I have been struggling for weeks to even get the Sonoma installer to load. 

Using your EFI straight from your repo, I am able to boot the Sonoma installer and begin the installation. After the second restart where it is finishing up the installation with the Apple logo, it then goes into a reboot loop. It will begin to load and then the whole machine restarts.

When trying to make adjustments to your EFI, all I did was make matters worse.

System specs:
CPU: Intel Xeon E5-2670 v2 2.5GHZ 10 Core
Motherboard: Jingsha x79 mAtx (https://xeon-e5450.ru/socket-2011/motherboards/jingsha-x79-v0-1/)
RAM: 64GB DDR3 1066MHZ
HDD: 512gb NVME 
GPU: MSI RX580 Gaming-X 4GB (https://www.msi.com/Graphics-Card/Radeon-RX-580-GAMING-X-4G/support)

If you could help me, I would be eternally grateful.

I look forward to hearing from you.

Thank you.

**Comment by wy414012** [comment]
I have received your question and will help you handle it in the near future. This issue can also be self-resolved by modifying the DSDT CPU description section in the document. Alternatively, you can use the full DSDT patch. Please send me a copy of the motherboard BIOS firmware and I will take the time to address any bugs in the firmware.

**Comment by fromage9747** [comment]
@wy414012 Thank you so much for your response.  I have opened up SSDT-CPUM.aml using MaciASL and it is configured for my CPU, Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz:

![Screenshot 2023-11-30 at 17 48 33](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2/assets/23147783/c01f289f-f084-4cfd-87d6-e6fcefc82efa)

I have included the BIOS for the Jingsha x79 motherboard below:

[JS797007.zip](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2/files/13511804/JS797007.zip)

If I have misunderstood anything, let me know.

I look forward to your response.

**Comment by wy414012** [comment]
@fromage9747  Based on the firmware you provided, I have checked the built-in ACPI table and did not find the expected processor description keywords such as 'Processor (C000, 0x00, 0x00000400, 0x06)' or 'Scope (_PR.CPU0)', which may be due to errors in the built-in firmware and non-standard C600 x79 platforms from the manufacturer. Please provide the details under Windows。：
![image](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2/assets/36281137/2fb5d63a-4080-43c8-b35c-71b497851644)
Used to determine the mount location of your processor in ACPI, I will fix this bug for you.

**Comment by fromage9747** [comment]
@wy414012 Thank you for getting back to me. 

I have been able to obtain the information you were asking for.

From within Windows, these are the CPU BIOS Names for each device under the processor tree:

```
\_SB.P010
\_SB.P011
\_SB.P012
\_SB.P013
\_SB.P000
\_SB.P001
\_SB.P002
\_SB.P003
\_SB.P004
\_SB.P005
\_SB.P006
\_SB.P007
\_SB.P008
\_SB.P009
\_SB.P00A
\_SB.P00B
\_SB.P00C
\_SB.P00D
\_SB.P00E
\_SB.P00F

```

Whilst in the process of getting this information, I was able to obtain some more information on the Sonoma install prior to it restarting/shutting down. 

The system will hang/stop/get stuck on `Stuck on IOAPIC: Version 0x20 Vectors 64:87`

Thank you in advance for all your help!

**Comment by fromage9747** [comment]
@wy414012 Please let me know if you need anything else from me.  👍

**Comment by wy414012** [comment]
@fromage9747 
We have fixed the missing firmware for you. Please update it using the flashing method provided by your manufacturer. After flashing, remove the `ACPI` related patches from the macOS bootloader. Now the firmware can handle it completely and is no longer required.
[JS79_fix_ACPI.zip](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2/files/13553691/JS79_fix_ACPI.zip)

**Comment by fromage9747** [comment]
@wy414012 Wow!  Thank you for this!  I was finally able to get some time to flash my motherboard using a programmer.  Sonoma installed and booted after a few other tweaks from your description.


```
Misc-->Security-->SecureBootModel-->Default ->Disabled  

NVRAM-->Add-->csr-active-config-->EF0F0000

boot-args-->amfi=0x80
```

The only problem I am facing now is OCLP and getting the GPU patch.  OCLP refuses to believe that SIP is disabled.

I have made the change to `csr-active-config` and I have gone into recovery and set  `csrutil disable` but it still says that the currently booted SIP is (0x3ef).

I will do some more fiddling tomorrow but thank you so much for all your help!

**Comment by fromage9747** [comment]
@wy414012 Thank you.  Everything is working great! Please feel free to close this.

**Comment by wy414012** [comment]
@fromage9747 If you have any questions, please feel free to ask again.

**Comment by fromage9747** [comment]
@wy414012 Thank you.  After successfully completing a test install yesterday and then proceeding to upgrade my main macOS install, I have been encountering issues. Unfortunately, I have been unsuccessful to get OpenCore to write the MacOS boot up logs to the EFI folder.  It will only write the OpenCore logs.  I have replaced the Release OpenCore files with the Debug as well as made all the necessary changes to the config.plist as per the below guide:

https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html#config-changes

This was my process:

I have two drives, a main 512GB NVME drive for daily use and a 120GB SSD that I use for testing upgrades and installs of macOS. I successfully performed a fresh installation of Sonoma on my 120GB SSD and everything was running great, full metal support as well as running Android emulator, everything worked.  Once this was successful, I then proceeded to use this EFI to boot my BigSur instance on my 512GB NVME drive.  It booted successfully using my Sonoma EFI.

Next, I proceeded to perform an OS upgrade from BigSur to Sonoma.  It completed successfully, but once the Installation was complete and time to boot and display the OS, the machine reboots.  I thought, okay, I will try and investigate this by booting back into my Successful Sonoma install off the 120GB SSD.  Now this one won't boot either!

Last night I was eventually able to get back into my Sonoma install by using the EFI I had from the Sonoma USB installer after some fiddling.  So, great, SonomaTest drive is working, USB installer EFI is working.  Now let's try again on the 512GB NVME.

Same thing, restarts the machine.  Now my Sonoma won't boot and neither will the USB EFI. 

I have since proceeded to try and get the logs written to the EFI folder so that I can read through to see what the problem is, as it goes too fast on my screen.  Even my camera cannot capture everything but for some reason, OpenCore is only writing the OC debug lines and not the macOS lines.  There is a massive blank space in the log file where the macOS logs should be, though.

I have included them below for your reference.
[opencore-2023-12-09-044000.txt](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2/files/13622740/opencore-2023-12-09-044000.txt)

What really makes no sense is that even after NVRam Reset, I still cannot boot off of the already proven SonomaTest drive SSD. It is not logical.  Three separate EFI's and they are all affected and don't boot.

By the way, I still ended up needing to include the CPU SSDT in order to get it working again last night. 

I will continue to fight with it today.  All I need is to get a successful log file in order to proceed.  I don't know what it is not logging the macOS verbose logs to the EFI folder log file.

**Comment by wy414012** [comment]
@fromage9747 Based on the logs, I can clearly tell you that the boot parameter -amd_no_dgpu_accel amfi=0x80 cannot be used to boot systems with versions lower than 13.0+. After booting macOS14, the data will be stored in the nvram, resulting in an inability to start.

**Comment by fromage9747** [comment]
@wy414012 Yeah this is the logs from my USB installer which I was able to get it to load.  The actual Sonoma Test install EFI has this "-amd_no_dgpu_accel" removed. I will try removing "-amd_no_dgpu_accel amfi=0x80" and see again. Thank you for getting back to me.

**Comment by wy414012** [comment]
@fromage9747 If you want to upgrade from an older version to macOS 14.0, the OTA method is not available. You should boot to the 14.0+RE recovery partition and perform an`overwrite` installation, which will not lose data.

**Comment by fromage9747** [comment]
@wy414012 Do you think my main drive is still salvageable? If I perform an overwrite installation again? 

Below is the output after removing the above:

![20231209_125116](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2/assets/23147783/bc398634-e640-4b63-a2fb-bf8160f2008b)

I will chuck "amfi=0x80" to see if I can get further as that is what I needed before.

**Comment by wy414012** [comment]
@fromage9747 As long as you do not format the main drive, you can install macOS 14.0+ as a fresh installation, which will not lose existing data. Just apply the relevant patches.

**Comment by fromage9747** [comment]
@wy414012 Right, thank you for this.  Wish I had known before.  Now I just have to get this EFI to boot again and then I can proceed.  I appreciate your help.

**Comment by fromage9747** [comment]
@wy414012 It just makes no sense.  I can get it to work off the USB and then as soon as I transfer the working USB EFI to the SSD it fails and no matter how hard I try I cannot get the macOS boot log written to a file to review.  Pulling out my hair here from frustration. 

Booting the installer or recovery works without issue and now there is a new issue, it will randomly decide to not display the picker.  The screen is on and is receiving a signal, but the picker will not be displayed.  I feel the universe is out to get me today.

**Comment by fromage9747** [comment]
@wy414012 Success!

My main install that I upgraded to Sonoma from within the OS was causing all of my problems. I guess it was writing nonsense into the NVRam and persisting it constantly somewhere. 

I eventually gave up and just decided to try and overwrite install from the installer on my main drive. All the illogical problems went away.

Now I have Sonoma on my main drive with full metal support.

Thank you for all your help!

**Comment by fromage9747** [comment]
@wy414012 Just wanted to thank you again.

After a day of having my Hackintosh up and running, I discovered that there were issues for any Web View reliant Electron based apps.  They just wouldn't open.  I tested the same apps on my OCLP MacBook Pro 8,3 Sonoma, and they worked fine so I can't say for certain if this issue would not arise on a fresh installed Sonoma or not but what would happen if you opened apps like Slack, OpenVPN Connect, WhatsApp, Postman etc is that they would jump in the dock and then close OR they would open to a white screen and then close.

In order to resolve this issue, add the following boot-args:
ipc_control_port_options=0

Once that is added, all the apps work.

You may find this useful to add to your install instructions. 

Have an awesome day!
